import sqlite3

# Creación de tablas de la bd

sql_tabla_usuario = '''
CREATE TABLE USUARIO (ID_USUARIO INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT, 
    NOMB_USUARIO TEXT(20) NOT NULL, 
    EMAIL TEXT(40) NOT NULL, 
    ROL TEXT(15) NOT NULL,
    CONTRASENIA TEXT(16) NOT NULL
)
'''
sql_tabla_sesion = '''
CREATE TABLE SESION (ID_SESION INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    FECHA_HORA TEXT(20) NOT NULL,
    ID_USUARIO INTEGER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
)

'''

sql_tabla_cliente = '''
CREATE TABLE CLIENTE (ID_CLIENTE INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    NOMB_CLIENTE TEXT(20) NOT NULL,
    APELLIDO_CLIENTE TEXT(20) NOT NULL,
    DIRE_CLIENTE TEXT(20) NOT NULL,
	TEL_CLIENTE INTEGER(9),
    TOPE_CREDITO REAL(6) NOT NULL
)
'''

sql_tabla_proveedor = '''
CREATE TABLE PROVEEDOR (ID_PROV INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    NOMB_PROV TEXT(20) NOT NULL,
    DIRE_PROV TEXT(20) NOT NULL,
    TEL_PROV INTEGER(9) NOT NULL   
)
'''

sql_tabla_producto = '''
CREATE TABLE "PRODUCTO" (ID_PRODUCTO INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    NOMB_PRODUCTO TEXT(20) NOT NULL,
    PRECIO_COSTO REAL(6) NOT NULL,
    UTILIDAD INTEGER(3) NOT NULL,
    MEDIDA TEXT(15) NOT NULL,
    PRECIO_VENTA REAL(6) NOT NULL,
    CANTIDAD_STOCK INTEGER(3) NOT NULL,
    VENCIM_PROD TEXT(8) NOT NULL,
    CATEGORIA TEXT(20) NOT NULL
)
'''

sql_tabla_compra = '''
CREATE TABLE COMPRA (ID_COMPRA INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    NUM_FACT INTEGER(15) NOT NULL,
	FECHA_COMPRA TEXT(8) NOT NULL,
    NOMB_PROV TEXT(20) NOT NULL,
    NOMB_PRODUCTO TEXT(20) NOT NULL,
    CANT_PROD INTEGER(3) NOT NULL,	
    PRECIO_COSTO REAL(6) NOT NULL,
    SUBTOTAL_COMPRA REAL(6) NOT NULL,
    TOTAL_COMPRA REAL(6) NOT NULL,
    TIPO_COMPRA TEXT(8) NOT NULL
)
'''

sql_tabla_venta = '''
CREATE TABLE VENTA (NUM_VENTA INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    FECHA_VENTA TEXT(8) NOT NULL, 
    CANTIDAD INTEGER(3) NOT NULL,
    SUBTOTAL REAL(6) NOT NULL,
    TOTAL REAL(6) NOT NULL,
    TIPO_VENTA TEXT(8) NOT NULL,
    ID_PRODUCTO INTEGER,
	ID_CLIENTE INTEGER,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)
'''

sql_tabla_hace = '''
CREATE TABLE HACE(IDUSUARIO_IDCOMPRA INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    ID_USUARIO INTEGER,
    ID_COMPRA INTEGER, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA)
)
'''
sql_tabla_realiza = '''
CREATE TABLE REALIZA(IDUSUARIO_NUMVENTA INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT,
    ID_USUARIO INTEGER, 
    NUM_VENTA INTEGER, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (NUM_VENTA) REFERENCES VENTA(NUM_VENTA)
)
'''

sql_tabla_distribuida_por = '''
CREATE TABLE DISTRIBUIDA_POR (IDCOMPRA_IDPROV INTEGER PRIMARY KEY NOT NULL, AUTO_INCREMENT, 
	SALDO_PROV REAL(6) NOT NULL,
	FECHA_VENC_FACT TEXT(8) NOT NULL,
	ID_COMPRA INTEGER, 
	ID_PROV INTEGER, 
	FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
	FOREIGN KEY (ID_PROV) REFERENCES PROVEEDOR(ID_PROV)
)
'''

sql_tabla_tiene = '''
CREATE TABLE TIENE (NUMVENTA_IDPRODUCTO PRIMARY KEY  NOT NULL, AUTO_INCREMENT,
	NUM_VENTA INTEGER, 
	ID_PRODUCTO INTEGER, 
	FOREIGN KEY (NUM_VENTA) REFERENCES VENTA(NUM_VENTA),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
)
'''
sql_tabla_lleva = '''
CREATE TABLE LLEVA (NUMVENTA_IDCLIENTE PRIMARY KEY NOT NULL, AUTO_INCREMENT,
	NUM_VENTA INTEGER, 
	ID_CLIENTE INTEGER, 
	FOREIGN KEY (NUM_VENTA) REFERENCES VENTA(NUM_VENTA),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)
'''

sql_tabla_contiene = '''
CREATE TABLE CONTIENE(IDCOMPRA_IDPRODUCTO PRIMARY KEY NOT NULL, AUTO_INCREMENT, 
    ID_COMPRA INTEGER, 
    ID_PRODUCTO INTEGER, 
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA), 
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
)
'''
sql_tabla_saldo = '''
CREATE TABLE SALDO (ID_SALDO PRIMARY KEY NOT NULL, AUTO_INCREMENT, 
    SALDO_CLIENTE REAL(10) NOT NULL,
    ID_CLIENTE INTEGER, 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)    
)
'''

if __name__ == '__main__':
    try:
        print('Creando base de datos Almacen..')
        conexion = sqlite3.connect('../../almacen.db')

        print('Creando tablas en base de datos Almacen..')
        conexion.execute(sql_tabla_usuario)
        conexion.execute(sql_tabla_sesion)
        conexion.execute(sql_tabla_cliente)
        conexion.execute(sql_tabla_proveedor)
        conexion.execute(sql_tabla_producto)
        conexion.execute(sql_tabla_compra)
        conexion.execute(sql_tabla_venta)
        conexion.execute(sql_tabla_hace)
        conexion.execute(sql_tabla_realiza)
        conexion.execute(sql_tabla_distribuida_por)
        conexion.execute(sql_tabla_tiene)
        conexion.execute(sql_tabla_lleva)
        conexion.execute(sql_tabla_contiene)
        conexion.execute(sql_tabla_saldo)

        conexion.close()
        print('Tablas creadas exitosamente.')
    except Exception as e:
        print(f'Hubo un error al crear base de datos Almacen: {e}', e)
